### ISSUE TITLE
This algorithm seems to not be implemented in Chrome 59 beta

### ISSUE THREAD

**Issue by tometzky** [sleevi/explainer#1]
I've just checked a latest Chrome 59 beta for Linux 64bit `Version 59.0.3071.83 (Official Build) beta (64-bit)` and Chrome 60 dev for Linux 64bit `Version 60.0.3112.10 (Official Build) dev (64-bit)` and they both accepted our GeoTrust wildcard certificate with 1187 days valid period (over 3 years, from 2015-12-07 to 2019-03-07).

Is this implementation pushed back to some later Chrome version and the algorithm here should be corrected? It's valuable to know how much time we have left to migrate.

**Comment by sleevi** [comment]
Correct. This was the textual description for an initial proposal, discussed at https://groups.google.com/a/chromium.org/d/msg/blink-dev/eUAKwjihhBs/rpxMXjZHCQAJ

This proposal has since been updated and is being discussed on the same thread. See https://groups.google.com/a/chromium.org/d/msg/blink-dev/eUAKwjihhBs/ovLalSBRBQAJ and subsequent messages.
